version: "3.3"

services:
  broker:
    image: eclipse-mosquitto:2.0.10
    ports:
      - 1883:1883
      - 1884:9001
    volumes:
      - ./broker/config:/mosquitto/config
      - broker-data:/mosquitto/data
      - broker-logs:/mosquitto/logs

volumes:
  broker-data:
  broker-logs:
