version: "3.3"

services:
  mosquitto:
    image: eclipse-mosquitto:2.0.10
    ports:
      - 1883:1883
      - 1884:9001
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto-data:/mosquitto/data
      - mosquitto-logs:/mosquitto/logs
    restart: always

volumes:
  mosquitto-data:
  mosquitto-logs:
